{"uid":"9765fb281544f394","name":"test_lock_unlock_configuration[chromium]","fullName":"tests.Automation_tests.test_admin_playout#test_lock_unlock_configuration","historyId":"35e37892361227fcf4f40afc85f53c6e","time":{"start":1758895245233,"stop":1758895245233,"duration":0},"description":"\n    Tests the lock and unlock functionality for a row with input area and dropdowns.\n    Verifies that the input area and dropdowns are not interactable when locked and interactable when unlocked.\n    ","descriptionHtml":"<pre><code>Tests the lock and unlock functionality for a row with input area and dropdowns.\nVerifies that the input area and dropdowns are not interactable when locked and interactable when unlocked.\n</code></pre>\n","status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113781c90>: Failed to establish a new connection: [Errno 51] Network is unreachable'))","statusTrace":"E   OSError: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x113781c90>: Failed to establish a new connection: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113781c90>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113781c90>: Failed to establish a new connection: [Errno 51] Network is unreachable'))","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"test_setup","time":{"start":1758892666166,"stop":1758892674974,"duration":8808},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"base_url","time":{"start":1758892666166,"stop":1758892666166,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"pytestconfig","time":{"start":1758892666166,"stop":1758892666166,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"delete_output_dir","time":{"start":1758892666166,"stop":1758892666166,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"check_if_secrets_are_loaded","time":{"start":1758892666166,"stop":1758892666166,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"_verify_url","time":{"start":1758892666166,"stop":1758892666166,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"rp_logger","time":{"start":1758892674974,"stop":1758892674974,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"playwright","time":{"start":1758892674975,"stop":1758892675126,"duration":151},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"browser_type_launch_args","time":{"start":1758892674975,"stop":1758892674975,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"browser","time":{"start":1758892675127,"stop":1758892675553,"duration":426},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"launch_browser","time":{"start":1758892675127,"stop":1758892675127,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"browser_type","time":{"start":1758892675127,"stop":1758892675127,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"admin_user","time":{"start":1758895245233,"stop":1758895245234,"duration":1},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113781c90>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n","statusTrace":"  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/conftest.py\", line 125, in fixture_admin_user\n    tokenized_user = API(api_util.auto_admin_user[\"username\"], api_util.auto_admin_user[\"password\"])\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 20, in __init__\n    self.token = get_access_token(username, password)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 12, in get_access_token\n    token_request = requests.post(f\"{API_URL}/authenticate\", json=auth, verify=False, timeout=10)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"afterStages":[{"name":"browser::0","time":{"start":1758895245261,"stop":1758895245321,"duration":60},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"playwright::0","time":{"start":1758895245322,"stop":1758895245324,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"test_setup::0","time":{"start":1758895245325,"stop":1758895245327,"duration":2},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11378e190>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n","statusTrace":"  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/conftest.py\", line 101, in fixture_test_setup\n    FileDistributor().remove_all_disribution_process()\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/component_util/file_distributor.py\", line 74, in remove_all_disribution_process\n    response, status = API().get(\"/distributionprocesses\")\n                       ^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 20, in __init__\n    self.token = get_access_token(username, password)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 12, in get_access_token\n    token_request = requests.post(f\"{API_URL}/authenticate\", json=auth, verify=False, timeout=10)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"labels":[{"name":"feature","value":"AdminPlayout"},{"name":"parentSuite","value":"tests.Automation_tests"},{"name":"suite","value":"test_admin_playout"},{"name":"host","value":"TR-GKJF6LPM4P"},{"name":"thread","value":"77029-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.Automation_tests.test_admin_playout"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'chromium'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[]}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":17,"unknown":0,"total":20},"items":[{"uid":"1bdf6534c06053d0","status":"passed","time":{"start":1758805880176,"stop":1758805956913,"duration":76737}},{"uid":"a26b37bf7f1398da","status":"passed","time":{"start":1758710719257,"stop":1758710789923,"duration":70666}},{"uid":"fe0cae47c3e01d7d","status":"passed","time":{"start":1758547896192,"stop":1758547983640,"duration":87448}},{"uid":"3e73117d1f350556","status":"passed","time":{"start":1758539414775,"stop":1758539491600,"duration":76825}},{"uid":"c83c55109428a8ec","status":"passed","time":{"start":1758538209449,"stop":1758538285236,"duration":75787}},{"uid":"cf3bd1553b385df5","status":"passed","time":{"start":1758537005675,"stop":1758537082361,"duration":76686}},{"uid":"84904c5cd3d47a4f","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//*[@id=\\\"app-root\\\"]/div[3]/main/div[2]/article/div/div[2]/div[1]/label[2]\")","time":{"start":1757326674108,"stop":1757326710778,"duration":36670}},{"uid":"dbb68a16e00a381","status":"passed","time":{"start":1757316085949,"stop":1757316161180,"duration":75231}},{"uid":"7481210f2dced1e3","status":"passed","time":{"start":1756106164953,"stop":1756106242817,"duration":77864}},{"uid":"23e9bc1483e627df","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//*[@id=\\\"app-root\\\"]/div[3]/main/div[2]/article/div/div[2]/div[1]/label[2]\")","time":{"start":1756102625091,"stop":1756102662297,"duration":37206}},{"uid":"e65a8850f32816c2","status":"passed","time":{"start":1755861333326,"stop":1755861403839,"duration":70513}},{"uid":"35370505fb9c766","status":"passed","time":{"start":1755849529136,"stop":1755849599765,"duration":70629}},{"uid":"c214f0f36e7f5b04","status":"passed","time":{"start":1755770623605,"stop":1755770702479,"duration":78874}},{"uid":"b150fec200ede002","status":"passed","time":{"start":1754668047202,"stop":1754668123113,"duration":75911}},{"uid":"e53c141b59d77f77","status":"passed","time":{"start":1754305875494,"stop":1754305970084,"duration":94590}},{"uid":"d4e7fcf94b6b067a","status":"passed","time":{"start":1754046946156,"stop":1754047016854,"duration":70698}},{"uid":"3ff1d9aa17f75c65","status":"passed","time":{"start":1754036593985,"stop":1754036664611,"duration":70626}},{"uid":"f084439402bc82f5","status":"passed","time":{"start":1754032874581,"stop":1754032945223,"duration":70642}},{"uid":"35503f519be18401","status":"passed","time":{"start":1749553015301,"stop":1749553091875,"duration":76574}}]},"tags":[]},"source":"9765fb281544f394.json","parameterValues":["'chromium'"]}