{"name": "test_distribution_history[chromium]", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to find story 'QA-JSON-DD-30-DAY-FEATURE-REFEED-2' in history page.", "trace": "E   AssertionError: Locator expected to be visible\n    Actual value: <element(s) not found> \n    Call log:\n    LocatorAssertions.to_be_visible with timeout 5000ms\n      - waiting for locator(\"text=\\\"QA-JSON-DD-30-DAY-FEATURE-REFEED-2\\\"\")\n\nThe above exception was the direct cause of the following exception:\nE   AssertionError: Failed to find story 'QA-JSON-DD-30-DAY-FEATURE-REFEED-2' in history page."}, "attachments": [{"name": "log", "source": "12912591-a8c3-46b3-9c8e-89e240ee6ff5-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "6cd99b72-9610-4a0b-8c07-75641dceea47-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1749194904377, "stop": 1749195020068, "uuid": "49674a11-cd09-4912-91aa-dae865b3411b", "historyId": "ae818eedf9027076ac5f968ef82e5282", "testCaseId": "500796d15862b4c914eca89da2581a08", "fullName": "tests.Automation_tests.test_history#test_distribution_history", "labels": [{"name": "feature", "value": "History"}, {"name": "parentSuite", "value": "tests.Automation_tests"}, {"name": "suite", "value": "test_history"}, {"name": "host", "value": "TR-GKJF6LPM4P"}, {"name": "thread", "value": "22581-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Automation_tests.test_history"}]}