{"uuid": "405911fa-cc2f-40ab-ac0a-dce7bb16a21d", "children": ["d0d85dd7-f78b-450f-a089-5e6b75e90156", "4073cd41-f58b-456c-b59d-3f9b0e79ce1c", "88c09f3d-a3d8-49c0-9f55-64309c855d45", "6e2c7ed9-0f81-4046-a04c-996064433160", "21e61913-b741-48d8-81f4-46e38c8bd1ab"], "befores": [{"name": "test_setup", "status": "passed", "start": 1758886296769, "stop": 1758886297436}], "afters": [{"name": "test_setup::0", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1120c07d0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n", "trace": "  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/conftest.py\", line 101, in fixture_test_setup\n    FileDistributor().remove_all_disribution_process()\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/component_util/file_distributor.py\", line 74, in remove_all_disribution_process\n    response, status = API().get(\"/distributionprocesses\")\n                       ^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 20, in __init__\n    self.token = get_access_token(username, password)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 12, in get_access_token\n    token_request = requests.post(f\"{API_URL}/authenticate\", json=auth, verify=False, timeout=10)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1758887149887, "stop": 1758887149890}], "start": 1758886296769, "stop": 1758887149890}