{"uid":"8d8af85d268c6160","name":"test_clear_all_items_playout_history[chromium]","fullName":"tests.Automation_tests.test_admin_playout#test_clear_all_items_playout_history","historyId":"253ff02ae4f82bcd12998af8a41ad44a","time":{"start":1758895245222,"stop":1758895245222,"duration":0},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117de1950>: Failed to establish a new connection: [Errno 51] Network is unreachable'))","statusTrace":"E   OSError: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x117de1950>: Failed to establish a new connection: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117de1950>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117de1950>: Failed to establish a new connection: [Errno 51] Network is unreachable'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"test_setup","time":{"start":1758892666166,"stop":1758892674974,"duration":8808},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"base_url","time":{"start":1758892666166,"stop":1758892666166,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"pytestconfig","time":{"start":1758892666166,"stop":1758892666166,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"delete_output_dir","time":{"start":1758892666166,"stop":1758892666166,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"check_if_secrets_are_loaded","time":{"start":1758892666166,"stop":1758892666166,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"_verify_url","time":{"start":1758892666166,"stop":1758892666166,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"rp_logger","time":{"start":1758892674974,"stop":1758892674974,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"playwright","time":{"start":1758892674975,"stop":1758892675126,"duration":151},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"browser_type_launch_args","time":{"start":1758892674975,"stop":1758892674975,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"browser","time":{"start":1758892675127,"stop":1758892675553,"duration":426},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"launch_browser","time":{"start":1758892675127,"stop":1758892675127,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"browser_type","time":{"start":1758892675127,"stop":1758892675127,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"admin_user","time":{"start":1758895245223,"stop":1758895245224,"duration":1},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117de1950>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n","statusTrace":"  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/conftest.py\", line 125, in fixture_admin_user\n    tokenized_user = API(api_util.auto_admin_user[\"username\"], api_util.auto_admin_user[\"password\"])\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 20, in __init__\n    self.token = get_access_token(username, password)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 12, in get_access_token\n    token_request = requests.post(f\"{API_URL}/authenticate\", json=auth, verify=False, timeout=10)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"afterStages":[{"name":"browser::0","time":{"start":1758895245261,"stop":1758895245321,"duration":60},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"playwright::0","time":{"start":1758895245322,"stop":1758895245324,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"test_setup::0","time":{"start":1758895245325,"stop":1758895245327,"duration":2},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11378e190>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n","statusTrace":"  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/conftest.py\", line 101, in fixture_test_setup\n    FileDistributor().remove_all_disribution_process()\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/component_util/file_distributor.py\", line 74, in remove_all_disribution_process\n    response, status = API().get(\"/distributionprocesses\")\n                       ^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 20, in __init__\n    self.token = get_access_token(username, password)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 12, in get_access_token\n    token_request = requests.post(f\"{API_URL}/authenticate\", json=auth, verify=False, timeout=10)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"labels":[{"name":"feature","value":"AdminPlayout"},{"name":"parentSuite","value":"tests.Automation_tests"},{"name":"suite","value":"test_admin_playout"},{"name":"host","value":"TR-GKJF6LPM4P"},{"name":"thread","value":"77029-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.Automation_tests.test_admin_playout"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'chromium'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[]}],"history":{"statistic":{"failed":0,"broken":9,"skipped":0,"passed":10,"unknown":0,"total":19},"items":[{"uid":"835e35e8007bf683","status":"broken","statusDetails":"NameError: name 'story_page' is not defined","time":{"start":1758805804417,"stop":1758805878811,"duration":74394}},{"uid":"5bb5a7bd95bd4f23","status":"broken","statusDetails":"NameError: name 'story_page' is not defined","time":{"start":1758710657551,"stop":1758710718651,"duration":61100}},{"uid":"c158a6e98a7c2883","status":"broken","statusDetails":"NameError: name 'story_page' is not defined","time":{"start":1758547809813,"stop":1758547894314,"duration":84501}},{"uid":"dcbb1e11b21eb717","status":"passed","time":{"start":1758539334750,"stop":1758539413470,"duration":78720}},{"uid":"a0caf4097b4333a8","status":"passed","time":{"start":1758538127180,"stop":1758538207944,"duration":80764}},{"uid":"4f2c3cafbdc97d03","status":"passed","time":{"start":1758536869567,"stop":1758536948915,"duration":79348}},{"uid":"be751e2a34dfa587","status":"passed","time":{"start":1757326592889,"stop":1757326672834,"duration":79945}},{"uid":"2f7751c2f6659e70","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//*[@id=\\\"app-root\\\"]/div[3]/main/div[2]/div[1]/div/button[2]\")","time":{"start":1757315984911,"stop":1757316084977,"duration":100066}},{"uid":"22c8f229bdcee44f","status":"passed","time":{"start":1756102543440,"stop":1756102623863,"duration":80423}},{"uid":"fe8b2fecf285e63","status":"passed","time":{"start":1755861266855,"stop":1755861332932,"duration":66077}},{"uid":"a26a3b034861bf8a","status":"passed","time":{"start":1755849462618,"stop":1755849528726,"duration":66108}},{"uid":"abf8d83456f3a31c","status":"passed","time":{"start":1755770542386,"stop":1755770622288,"duration":79902}},{"uid":"c9ed464dd300a7f","status":"passed","time":{"start":1754667965445,"stop":1754668045981,"duration":80536}},{"uid":"16046a1a182e9723","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"http://10.189.200.6/admin/playout\", waiting until \"load\"","time":{"start":1754305809444,"stop":1754305843110,"duration":33666}},{"uid":"c2f7e741ddc307d1","status":"passed","time":{"start":1754046879694,"stop":1754046945767,"duration":66073}},{"uid":"fd8ca50b1898aa0e","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//div[@class=\\\"list column\\\"]//div[1]//div[@data-name=\\\"source\\\"]//div//ul//li[5]\")","time":{"start":1754036553164,"stop":1754036593459,"duration":40295}},{"uid":"4ef2a9df452726b6","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//div[@class=\\\"list column\\\"]//div[1]//div[@data-name=\\\"source\\\"]//div//ul//li[5]\")","time":{"start":1754032833815,"stop":1754032874134,"duration":40319}},{"uid":"e064a7b8c68e1b03","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//*[@id=\\\"app-root\\\"]/div[3]/main/div[2]/div[1]/div/button[2]\")","time":{"start":1749552911725,"stop":1749553013966,"duration":102241}}]},"tags":[]},"source":"8d8af85d268c6160.json","parameterValues":["'chromium'"]}