INFO     root:test_VFD.py:415 Validation from database
INFO     root:database.py:28 (56, 'KZBZokoU', '$2a$10$fsW3IeWEkVs70RCAVPt.Ge8a45jJMVN3WbPlYVmOFK/HsoZAuMU.O', None, None, 1, 1, 1, 1)
INFO     root:database.py:28 (526, '10.99.13.11', 'wneqa', 'nBhon2VaoHA8Fp8SpXnV+A==', 21, 0, '/wneclient/data/QA/ftp/files/testJakub', None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0, 0, None, None, 0, None, 'tls', None, 'http', 0, None, 'tls', None, 'http', None, None, None, None, None)