{"name": "test_clear_all_items_playout_history[chromium]", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117de1950>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "trace": "E   OSError: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x117de1950>: Failed to establish a new connection: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117de1950>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x117de1950>: Failed to establish a new connection: [Errno 51] Network is unreachable'))"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1758895245222, "stop": 1758895245222, "uuid": "47b57ea4-b80d-4ad4-918d-d76f8e0c178b", "historyId": "253ff02ae4f82bcd12998af8a41ad44a", "testCaseId": "ac2caa6bc9291d0c5ab192f2a5e9ab4a", "fullName": "tests.Automation_tests.test_admin_playout#test_clear_all_items_playout_history", "labels": [{"name": "feature", "value": "AdminPlayout"}, {"name": "parentSuite", "value": "tests.Automation_tests"}, {"name": "suite", "value": "test_admin_playout"}, {"name": "host", "value": "TR-GKJF6LPM4P"}, {"name": "thread", "value": "77029-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Automation_tests.test_admin_playout"}]}